### ISSUE TITLE
About jsx

### ISSUE THREAD

**Issue by Zen33** [apeschar/esbuild-vue#12]
The esbuild default jsxFactory is React. There was not an open render function from Vue 2.x, so how 'esbuild-vue' deal with jsx?  Thanks.

**Comment by apeschar** [comment]
No idea, I don't use JSX with Vue 2.

You might be able to configure esbuild to use Vue's createElement.

See: https://esbuild.github.io/content-types/#jsx

I suspect it won't work because Vue's createElement has a strange signature requiring props to be split from attributes, etc. Maybe some sort of adapter could be made to work.

For example: https://www.npmjs.com/package/rollup-plugin-vue-jsx-compat

**Comment by Zen33** [comment]
Thanks :)
