### ISSUE TITLE
Esbuild keeps throwing errors on vue and ts files

### ISSUE THREAD

**Issue by pantelispanayiotou** [apeschar/esbuild-vue#19]
I am using this plugin as a hope to parse my vue and ts files that import vue files along with esbuild. I am getting the following errors: 
`Decorators can only be used with class declarations in TypeScript`
`Expected "class" after TypeScript decorator but found "const"`

My project is using react, vue and other dependencies. Is this plugin suitable for my case? It seems that it doesn't work. Do i need to transpile ts files to js first?

**Comment by apeschar** [comment]
That is interesting. It seems that esbuild-vue doesn't work with TypeScript. It's probably necessary to first compile the TypeScript to JavaScript before applying the Vue compiler. I'll have a look to see if I can achieve that.

See this issue as well: https://github.com/evanw/esbuild/issues/2069

**Comment by apeschar** [comment]
It's the Vue compiler that replaces `export default` with a variable assignment, and this breaks the decorator. We're using a version of the Vue compiler that is no longer supported because this projected is/was intended for use with the legacy Vue 2.

esbuild-vue should probably get a new release for Vue 3 using all the latest components. But that's currently not on my roadmap.

You can try rewriting your code.

Replace this:

~~~js
@Component(...)
export default class MyComponent { ... }
~~~

With:

~~~js
@Component(...)
class MyComponent { ... }

export default MyComponent;
~~~

By moving the `export default` to a separate line, the Vue compiler will not introduce the syntax error you're seeing.

**Comment by pantelispanayiotou** [comment]
Thank you so much for the workaround, it solved all of my issues!

**Comment by vokshirg** [comment]
What would you advice in this case?


```js
@Component({
  name: 'Page404'
})
export default class extends Vue {
  private message = '404 Page Not Found'
}
```

**Comment by apeschar** [comment]
You can use the same workaround:

~~~typescript
@Component({
  name: 'Page404'
})
class Page404 extends Vue {
  private message = '404 Page Not Found'
}

export default Page404;
~~~

The main thing is that you can't combine the `@` decorators with `export default`.

**Comment by He110te4m** [comment]
Is it possible to build this transformation into the plugin?

Check for `export default class XXX` before you begin processing the `.vue` file.
