### ISSUE TITLE
postcss.plugin migrate warning is shown

### ISSUE THREAD

**Issue by truong-go2joy** [apeschar/esbuild-vue#4]
Hi @apeschar !!!
- When I use esbuild-vue in my project with postcss ^8, I catch a warning

clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration

I have checked package esbuild-vue, and see if esbuild-vue installed, it'll install postcss and postcss.plugin together, but the version of that postcss is lower than current version (just "version": "6.0.23"). So some plugin attach was deprecated

**Comment by apeschar** [comment]
PostCSS 6 is not installed. This repo itself depends on version `>=6.0.0` which will install version 8 at the moment.

In any case, the error is probably emitted from the PostCSS used by the Vue component compiler. `@vue/component-compiler` depends on PostCSS 7 via `@vue/component-compiler-utils`:

https://github.com/vuejs/vue-component-compiler/blob/845a310d643ab99b50db1babee9fca0bba48302c/package.json#L66

https://github.com/vuejs/component-compiler-utils/blob/82a37174990e31eaec609887a0ec262f06b454dd/package.json#L63

The problem is that `@vue/component-compiler` is using the deprecated API:

https://github.com/vuejs/vue-component-compiler/blob/master/src/postcss-clean.ts#L6

This is outside the scope of this project. If the message bothers you, you should probably submit a PR on the `@vue/component-compiler` repo.

**Comment by brandonferens** [comment]
Yeah, you're right. I discovered that a few hours after my comment. Thanks for the reply!
