### ISSUE TITLE
Test case test failed with "expect css to be extracted"

### ISSUE THREAD

**Issue by czz362100** [apeschar/esbuild-vue#8]
![image](https://user-images.githubusercontent.com/37129738/135398556-bd24201b-6063-4155-92ba-1fadaacc5420.png)
this case cant't run successful.
did it should be change to like this?
![image](https://user-images.githubusercontent.com/37129738/135398805-9ce5636b-537b-4714-9a6e-4d5e122f56c7.png)

**Comment by apeschar** [comment]
It didn't work on Microsoft Windows because this platform uses backslashes `\` instead of forward slashes `/` to delimit directories.

I've pushed https://github.com/apeschar/esbuild-vue/commit/800e6d47fc7af28f6d6ed43f445c4cf85c17dc84 which fixes the test case so that it works both on Windows and Unix-like platforms.

**Comment by czz362100** [comment]
ok.tanks
