### ISSUE TITLE
Template errors don't include line number in .vue file

### ISSUE THREAD

**Issue by jvns** [apeschar/esbuild-vue#9]
When I try to compile a template with errors in the HTML, I get this message:

```
    {
      detail: undefined,
      location: {
        column: 24,
        file: 'src/main.js',
        length: 11,
        line: 2,
        lineText: 'export { default } from "./App.vue";',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: 'vue',
      text: 'tag <ul> has no matching end tag.'
    }
```

The `tag <ul> has no matching end tag.` error is great, but the error message doesn't tell me which line of `App.vue` this error happened on, which makes the error a lot more difficult to fix.

(Also, thank you for this plugin!)

**Comment by apeschar** [comment]
I've just released esbuild-vue 0.4.1 which adds a code fragment generated by the Vue template compiler to the error message.

It looks like this:

~~~
 > src/App.vue:12:23: error: [plugin: vue] Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.

3  |    <span class="InputField__Label">{{ label }}</span>
4  |    <slot />
5  |  </label>
   |
6  |  <what>
   |  ^^^^^^
7  |
    12 │ import InputField from "./components/InputField.vue";
       ╵                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~

It looks a bit inconsistent since the first fragment is generated by the Vue compiler and the second one by esbuild, but it is what it is.

Hope this helps. If not, feel free to reopen the issue.
